### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by hakula** [Polymer/core-icons#15]
I keep getting a 404 not found error which appears to be caused by webcomponents.js (line 4184) sending GET requests to:
- /components/core-icons/core-icons.html
- /components/core-icons/communication-icons.html

Seems like webcomponents.js assumes these component files will be located in the folder /components whereas with all others I'm guessing it assumes they will be in the same folder as its parent directory (bower_components/webcomponentsjs).

**Comment by jongeho1** [comment]
+1

**Comment by ebidel** [comment]
Pretty sure this was: https://github.com/Polymer/core-icon/commit/bcf1d7f1fce79a2af93af3c4577eb52c41cf1353

We've re-tagged core-icon at 0.5.5. Holler if you're still seeing it after `bower update`
